var _objTrans =
{

"(Only *.png,*.jpg,*.jpeg,*.bmp format, ${SIZE_LIMIT} and ${PIXEL_LIMIT} pixel maximum each.)" : "(Only *.png,*.jpg,*.jpeg,*.bmp format, ${SIZE_LIMIT} and ${PIXEL_LIMIT} pixel maximum each.)",
".CSV file template" : ".CSV file template",
".XML file template" : ".XML file template",
"01.jpg" : "01.jpg",
"01-exp50.jpg" : "01-exp50.jpg",
"02.jpg" : "02.jpg",
"02-exp50.jpg" : "02-exp50.jpg",
"03.jpg" : "03.jpg",
"03-exp50.jpg" : "03-exp50.jpg",
"04.jpg" : "04.jpg",
"04-exp50.jpg" : "04-exp50.jpg",
"05.jpg" : "05.jpg",
"05-exp50.jpg" : "05-exp50.jpg",
"06.jpg" : "06.jpg",
"06-exp50.jpg" : "06-exp50.jpg",
"07.jpg" : "07.jpg",
"07-exp50.jpg" : "07-exp50.jpg",
"08.jpg" : "08.jpg",
"08-exp50.jpg" : "08-exp50.jpg",
"09.jpg" : "09.jpg",
"09-exp50.jpg" : "09-exp50.jpg",
"10.jpg" : "10.jpg",
"1000Mbps Full Duplex" : "1000Mbps Full Duplex",
"100Mbps Full Duplex" : "100Mbps Full Duplex",
"100Mbps Half Duplex" : "100Mbps Half Duplex",
"10-exp50.jpg" : "10-exp50.jpg",
"10Mbps Full Duplex" : "10Mbps Full Duplex",
"10Mbps Half Duplex" : "10Mbps Half Duplex",
"10min" : "10min",
"12s" : "12s",
"15s" : "15s",
"180 Ring Workaround" : "180 Ring Workaround",
"1min" : "1min",
"2h" : "2h",
"2min" : "2min",
"30min" : "30min",
"30s" : "30s",
"3s" : "3s",
"404 (Not Found)" : "404 (Not Found)",
"480 (Temporarily Unavailable)" : "480 (Temporarily Unavailable)",
"486 (Busy Here)" : "486 (Busy Here)",
"5min" : "5min",
"600 (Busy Everywhere)" : "600 (Busy Everywhere)",
"603 (Decline)" : "603 (Decline)",
"802.1x" : "802.1x",
"802.1x Mode" : "802.1x Mode",
"9s" : "9s",
"AA Login" : "AA Login",
"AA UC Login Server" : "AA UC Login Server",
"AA UC Login Server Port" : "AA UC Login Server Port",
"AA UC Password" : "AA UC Password",
"AA UC User Name" : "AA UC Username",
"AA_Login" : "AA Login",
"AA_LoginOut" : "AA LoginOut",
"AALoginContent-note" : "<b>AA Login Content<b>",
"Accept SIP Trust Server Only" : "Accept SIP Trust Server Only",
"Account" : "Account",
"Account1" : "Account 1",
"Account1:" : "Account1:",
"Account10" : "Account 10",
"Account11" : "Account 11",
"Account12" : "Account 12",
"Account13" : "Account 13",
"Account14" : "Account 14",
"Account15" : "Account 15",
"Account16" : "Account 16",
"Account2" : "Account 2",
"Account2:" : "Account2:",
"Account3" : "Account 3",
"Account3:" : "Account3:",
"Account4" : "Account 4",
"Account4:" : "Account4:",
"Account5" : "Account 5",
"Account5:" : "Account5:",
"Account6" : "Account 6",
"Account7" : "Account 7",
"Account8" : "Account 8",
"Account9" : "Account 9",
"account-adv-note" : "<b>DTMF</b><br>It is the signal sent from the IP phone to the network, which is generated when pressing the IP phone’s keypad during a call.<br><br><br><b>Session Timer</b><br>It allows multiple participants (more than three) to join a call.<br><br><br><b>VQ-RTCPXR</b><br>The VQ-RTCPXR mechanism, complaint with RFC 6035, sends the service quality metric reports contained SIP PUBLISH messages to the central report collector.",
"account-assignment-note" : "<b>Account Assignment</b><br>CP930W is a conference device，you can only assign one outgoing line and one incoming line for the CP930W. And make sure that the outgoing line and the incoming line are the same line.</br>",
"account-basic-note" : "<b>Anonymous Call</b><br>It allows the callers to block their caller ID information shown to the callee.<br><br><b>Anonymous Call Rejection</b><br>Reject the anonymous calls automatically.<br>",
"account-codec-note" : "<b>Audio Codecs</b><br>The audio codec to be used should be supported by the SIP server.<br><br>During the call, the IP phone offers the enabled audio codec list to the server, and then the server uses the audio codec negotiated with the called party according to the priority.<br>",
"account-handsetname-note" : "<b>Handset Name</b>",
"account-register-note" : "<b>Account Registration</b><br>Register account (s) for the IP phone.<br><br><b>Server Redundancy</b><br>It is often required in VoIP development to ensure service continuity, for events where the server needs to be taken offline for maintenance, or for events when the connection between the IP phone and the server fails.<br><br><b>NAT Traversal</b><br>A computer networking technique of establishing and maintaining Internet protocol connections across gateways that implement NAT.<br><br><br>You can configure NAT traversal for this account.<br>",
"AccountStatusId" : "AccountStatusId",
"ACD" : "ACD",
"ACD Trace" : "ACD Trace",
"ACD:" : "ACD",
"ACS Password" : "ACS Password",
"ACS URL" : "ACS URL",
"ACS Username" : "ACS Username",
"Action URI Allow IP List" : "Action URI Allow IP List",
"Active" : "Active",
"Active Backlight Level" : "Backlight Active Level",
"Adaptive" : "Adaptive",
"Add" : "Add",
"admin" : "Admin",
"Advanced" : "Advanced",
"Advice Of Charge" : "Advice of Charge",
"AES" : "AES",
"After Ring Time(0~120s)" : "After Ring Time (0~120s)",
"All" : "All",
"All Certificates" : "All Certificates",
"All Settings" : "All Settings",
"Allow IP Call" : "Allow IP Call",
"Allow SIP Authentication For XSI" : "Allow SIP Authentication for XSI",
"Always" : "Always",
"Always Forward" : "Always Forward",
"Always Off" : "Always Off",
"Always On" : "Always On",
"AlwaysOff" : "Always Off",
"AM" : "AM",
"AMR license" : "AMR License",
"AMR(oct=0)" : "AMR (oct=0)",
"AMR(oct=1)" : "AMR (oct=1)",
"AMR-WB(oct=0)" : "AMR-WB (oct=0)",
"AMR-WB(oct=1)" : "AMR-WB (oct=1)",
"And the browser must not be closed or refreshed!" : "And you cannot close or refresh the browser!",
"Anonymous" : "Anonymous",
"Anonymous Identity" : "Anonymous Identity",
"Anonymous Rejection" : "Anonymous Rejection",
"AnonymousCall OffCode can not contain ! and &." : "Anonymous call offcode cannot contain! and &.",
"AnonymousCall OnCode can not contain ! and &." : "AnonymousCall OnCode cannot contain! and &.",
"AnonymousReject OffCode can not contain ! and &." : "Anonymous reject offcode cannot contain! and &.",
"AnonymousReject OnCode can not contain ! and &." : "Anonymous reject oncode cannot contain! and &.",
"Answer" : "Answer",
"AOC Display Time" : "AOC Display Time",
"App" : "App",
"Applications" : "Applications",
"apps-broadsoftXMPP-note" : "<b>Broadsoft XMPP</b>",
"apps-broadsoftXSI-note" : "<b>Broadsoft XSI</b>",
"Apr" : "Apr",
"April" : "April",
"Are you sure delete user-defined factory config?" : "Are you sure to delete user-defined factory config?",
"Are you sure to remove the photo?" : "Are you sure to delete the selected photo?",
"Are you sure to remove the ringtone?" : "Are you sure to delete the ringtone?",
"Are you sure to remove the screensaver?" : "Are you sure to delete the screensaver?",
"Are you sure to remove the wallpaper?" : "Are you sure to delete the wallpaper?",
"Are you sure to set a blank password?" : "Are you sure to set a blank password?",
"Area Code" : "Area Code",
"Ask customers downloading status failed!!" : "Ask customers downloading status failed!!",
"Attempt Expired Time(s)" : "Attempt Expired Time (s)",
"Attendant Group" : "Attendant Group",
"Attended Tranfer" : "Attended Transfer",
"Attended Transfer" : "Attended Transfer",
"Attended Transfer On Hook" : "Attended Transfer on Hook",
"Audio" : "Audio",
"Audio & Video" : "Audio & Video",
"Audio Alert for BLF Pickup" : "Audio Alert for BLF Pickup",
"Audio Alert For Parked Call" : "Audio Alert for Parked Call",
"Audio Codecs" : "Audio Codecs",
"Audio Settings" : "Audio Settings",
"Aug" : "Aug",
"August" : "August",
"Australia" : "Australia",
"Austria" : "Austria",
"auth error" : "Auth error!",
"Authenticated Provisioning" : "Authenticated Provisioning",
"Authenticated_Provisioning" : "Authenticated_Provisioning",
"Auto" : "Auto",
"Auto BLF List" : "Auto BLF List",
"Auto Logout Time(1~1000min)" : "Auto Logout Time (1~1000min)",
"Auto Negotiation" : "Auto Negotiation",
"Auto Provision" : "Auto Provision",
"Auto Provision Now" : "Auto Provision Now",
"Automatic" : "Automatic",
"AutoRedialInterval should be a number !!" : "Auto Redial Interval should be a number!",
"AutoRedialTimes should be a number !!" : "Auto Redial Times should be a number!",
"Available" : "Available",
"B Transfer" : "Blind Transfer",
"Back" : "Back",
"BakOutboundPort should be a number !!" : "Back Outbound Port should be a number!",
"Base" : "Base",
"Base PIN" : "Base PIN",
"Base Unit PIN" : "Base Unit PIN",
"Basic" : "Basic",
"Basic Call Park" : "Basic Park",
"Begin time can't be later than end time!" : "Begin time should be earlier than end time!",
"Belgium" : "Belgium",
"BeTransferred" : "Be Transferred",
"BIN Configuration" : "BIN Configuration",
"BLA" : "BLA",
"BLF" : "BLF",
"BLF List" : "BLF List",
"BLF List Barge In Code" : "BLF List Barge in Code",
"BLF List Call Parked Code" : "BLF List Call Parked Code",
"BLF List Pickup Code" : "BLF List Pickup Code",
"BLF List Retrieve Call Parked Code" : "BLF List Retrieve Call Parked Code",
"BLF List URI" : "BLF List URI",
"Blind Transfer" : "Blind Transfer",
"Blind Transfer On Hook" : "Blind Transfer on Hook",
"Block Out" : "Block Out",
"BlockOut Number" : "BlockOut Number",
"Bluetooth" : "Bluetooth",
"boot.log" : "boot.log",
"Brazil" : "Brazil",
"Bridge" : "Bridge",
"Broadsoft" : "Broadsoft",
"Broadsoft Active" : "Broadsoft Active",
"BroadSoft Buddies" : "Network Buddies",
"Broadsoft XMPP" : "Broadsoft XMPP",
"Broadsoft XSI" : "Broadsoft XSI",
"BroadworksCallpark" : "Broadsoft Callpark",
"Browse" : "Browse",
"Browse..." : "Browse...",
"Buddies" : "Buddies",
"Busy" : "Busy",
"Busy Forward" : "Busy Forward",
"Busy Tone Delay (Seconds)" : "Busy Tone Delay (Seconds)",
"CA Certificates" : "CA Certificates",
"Call back" : "Call Back",
"Call Display" : "Call Display",
"Call Failed" : "Call Failed",
"Call Information Display Method" : "Call Information Display Method",
"Call List Show Method" : "Call List Display Mode",
"Call List Show Number" : "Call List Show Number",
"Call Log" : "Call Log",
"Call Number Filter" : "Call Number Filter",
"Call Park" : "Call Park",
"Call Park Code" : "Call Park Code",
"Call Park Mode" : "Call Park Mode",
"Call Pickup" : "Call Pickup",
"Call Pull Feature access code" : "Call Pull Feature Access Code",
"Call Return" : "Recall",
"Call Shift" : "Call Shift",
"Call Success" : "Call Successfully",
"Call Waiting" : "Call Waiting",
"Call Waiting Off Code" : "Call Waiting Off Code",
"Call Waiting On Code" : "Call Waiting On Code",
"Call Waiting Tone" : "Call Waiting Tone",
"Caller ID Source" : "Caller ID Source",
"CallIn" : "Incoming Call",
"Calling" : "Calling",
"Can not contain characters" : "Cannot contain characters",
"Cancel" : "Cancel",
"Cannot be empty!" : "Invalid value!",
"CDP" : "CDP",
"CFG Configuration" : "CFG Configuration",
"Channel" : "Channel",
"Chile" : "Chile",
"China" : "China",
"Chinese_S" : "简体中文 (Chinese Simplified)",
"Chinese_T" : "繁體中文 (Chinese Traditional)",
"Cipher Type" : "Cipher Type",
"Clear all static.* settings?" : "Reset all static.* settings?",
"Clear all userdata & local config?" : "Reset all userdata & local config?",
"Clear local.cfg settings?" : "Reset local.cfg settings?",
"Clear non-static settings?" : "Reset non-static settings?",
"clock daemon (note 2)" : "Clock Daemon (Note 2)",
"clock daemon(note 2)" : "Clock Daemon (Note 2)",
"Close Power Light" : "Close Power Light",
"CM  Key" : "CM Key",
"CNG" : "CNG",
"Code" : "Code",
"Codec" : "Codec",
"Command" : "Command",
"Common" : "Common",
"Common AES Key" : "Common AES Key",
"Common Name Validation" : "Common Name Validation",
"Common Power Light On" : "Common Power Light on",
"Compulsory" : "Compulsory",
"CONF" : "CONF",
"Conf Far Mute" : "Conf Far Mute",
"Conf Remove" : "Conf Remove",
"Conference" : "Conference",
"Conference Type" : "Conference Type",
"Conference URI" : "Conference URI",
"ConferencedHold" : "Conference Hold",
"ConferencedNewCallIn" : "Conference NewCall in",
"ConferenceManager" : "Conference Manager",
"Config File" : "Config File",
"Config has changed!" : "Config has changed!",
"ConfigSync" : "Sync Config ",
"ConfigSyncDownLoadURL" : "Sync Download URL Config ",
"ConfigSyncEnable" : "Sync Config Enable",
"ConfigSyncPassword" : "Sync Password Config ",
"ConfigSyncUpLoadURL" : "Sync Upload URL Config ",
"ConfigSyncUsername" : "Sync Username Config ",
"Configuration" : "Configuration",
"Configuration updating ..." : "Configuration updating ...",
"Configuration updating, please wait!" : "Configuration updating, please wait!",
"Confirm" : "Confirm",
"Confirm & Refresh" : "Confirm & Refresh",
"Confirm Base PIN" : "Confirm Base PIN",
"Confirm Password" : "Confirm Password",
"Congestion" : "Congestion",
"Connect" : "Connect",
"Connection Request Password" : "Connection Request Password",
"Connection Request Username" : "Connection Request Username",
"Contacts" : "Directory",
"Contacts:The operation is complete!" : "Contacts: Operation completed!",
"contactsbasic-note" : "<b>Local Directory</b><br>The built-in phone directory can store the names and phone numbers of your contacts.<br><br>You can add new groups and contacts, edit, delete or search for a contact, or simply dial a contact number from the local directory.<br><br>You can import or export the contact list.<br>",
"contacts-callinfo-note" : "<b>Call Log</b><br>It is a centrally maintained phone book, stored in the remote server.<br><br>Call log consists of four lists: Dialed List, Missed List, Received List, and Forwarded List.<br>",
"contacts-favorite-note" : "<b>Directory</b><br>It provides easy access to frequently used lists.<br><br><b>Search Source in Dialing</b><br>It allows the IP phone to automatically search entries from the search source list based on the entered string, and display results on the pre-dialing screen.<br><br><b>Recent Call In Dialing</b><br>It allows users to view the placed calls list when the phone is on the pre-dialing screen.",
"contacts-LDAP-note" : "<b>LDAP</b><br>LDAP (Lightweight Directory Access Protocol) is an application protocol for accessing and maintaining information services for the distributed directory over an IP network.</br><br>Yealink IP  phone  can interface with a corporate directory server that supports LDAP version 2 or 3 , such as  OpenLDAP, Microsoft Active Directory, Microsoft Active Directory Application Mode (ADAM) or Sun One Directory Server.</br><br>The Max Hits of LDAP is 1000.</br>",
"contacts-multicastIP-note" : "<b>Multicast Paging</b><br>Multicast paging allows IP phones to send/receive Real-time Transport Protocol (RTP) streams to/from the pre-configured multicast address (es)without SIP signaling. Up to 10 listening multicast addresses can be specified on the IP phone.<br>",
"contacts-note" : "<b>Contacts</b>",
"contacts-preview-note" : "<b>Contacts preview</b>",
"contacts-remote-note" : "<b>Remote Phone Book</b><br>It is a centrally maintained phone book, stored in the remote server.<br><br>Users only need the access URL of the remote phone book. The IP phone can establish a connection with the remote server and download the phone book, and then display the remote phone book entries on the phone user interface.<br>",
"Content shouldn't be empty!" : "Content cannot be empty!",
"Contrast" : "Contrast",
"Copy" : "Copy",
"Copyright © ${END_YEAR} ** Inc. All rights reserved." : "Copyright © ${END_YEAR} Yealink Inc. All rights reserved.",
"CPSource" : "CPSource",
"Critical Threshold For Delay" : "Critical Threshold for Delay",
"Critical Threshold For Moslq" : "Critical Threshold for Moslq",
"CSTA Control" : "CSTA Control",
"Current Base PIN" : "Current Base PIN",
"Custom" : "Custom",
"Custom Certificates" : "Custom Certificates",
"Custom Directory" : "Custom Directory",
"Custom Factory Config" : "Custom Factory Config",
"Custom Format" : "Custom Format",
"Custom Key" : "Custom Key",
"Custom Logo" : "Custom Logo",
"Custom Option Cannot Repeat!" : "Custom Option Cannot Repeat!",
"Custom Option Value Must Between 128 ~ 254!!" : "Custom Option value must be between 128 ~ 254!",
"CustomContact" : "Custom Contact",
"customer.png" : "Customer.png",
"Czech" : "Czech",
"Czech ETSI" : "Czech ETSI",
"Czechlang" : "Czech (Czech)",
"data" : "Data",
"Date" : "Date",
"Date Format" : "Date Format",
"Day" : "Day",
"Day of Week" : "Day of Week",
"Daylight Saving Time" : "Daylight Saving Time",
"days" : "days",
"DD MMM YYYY" : "DD MMM YYYY",
"DD/MM/YY" : "DD/MM/YY",
"DD/MM/YYYY" : "DD/MM/YYYY",
"DD-MMM-YY" : "DD-MMM-YY",
"Dec" : "Dec",
"December" : "December",
"Decline" : "Decline",
"Default" : "Default",
"Default Certificates" : "Default Certificates",
"Default Gateway" : "Default Gateway",
"Default password is in use. Please change!" : "Default password is in use. Please change!",
"Default.jpg" : "Default.jpg",
"Default-exp50.jpg" : "Default-exp50.jpg",
"Del" : "Del",
"Del Old Contact" : "Delete Old Contact",
"Delay must less than 300 !" : "Delay should be less than 300!",
"Delay must more than 0 !" : "Delay should be more than 0!",
"Delay must more than 20 !" : "Delay should be more than 20!",
"Delete" : "Delete",
"Delete Contacts" : "Delete contacts",
"Delete Handset" : "Delete Handset",
"Delete Old Contacts" : "Delete Old Contacts",
"Denmark" : "Denmark",
"Deploy" : "Deploy",
"Device Certificate" : "Device Certificate",
"Device Certificates" : "Device Certificates",
"DHCP" : "DHCP",
"DHCP Active" : "DHCP Active",
"DHCP Hostname" : "DHCP Hostname",
"DHCP Time" : "DHCP Time",
"DHCP VLAN" : "DHCP VLAN",
"DHCP_Server_Status" : "DHCP Server Status",
"Diagnostics" : "Diagnostics",
"Dial" : "Dial",
"Dial Now" : "Dial Now",
"Dial Now Rule" : "Dial Now Rule",
"Dial Plan" : "Dial Plan",
"DialCallPark" : "Dial Call Park",
"DialCallParkEmpty" : "Dial Call Park Empty",
"DialConference" : "Dial Conference",
"DialConferenceEmpty" : "Dial Conference Empty",
"DialDPickup" : "Dial DPickup",
"DialDPickupEmpty" : "Dial DPickup Empty",
"DialForward" : "Dial Forward",
"DialForwardEmpty" : "Dial Forward Empty",
"DialGroupCallPark" : "Dial Group Call Park",
"DialGroupCallParkEmpty" : "Dial Group Call Park Empty",
"Dialing" : "Dialing",
"DialingEmpty" : "Dialing Empty",
"Dial-now Rule should not be empty!" : "Dial-now Rule cannot be empty!",
"DialOnHold" : "Dial on Hold",
"DialRetrieve" : "Dial Retrieve",
"DialRetrieveEmpty" : "Dial Retrieve Empty",
"DialTrans" : "Transfer to",
"DialTransEmpty" : "Dial Trans Empty",
"Directed Call Pickup" : "Directed Call Pickup",
"Directed Call Pickup Code" : "Directed Call Pickup Code",
"Directories" : "Directory",
"Directory" : "Directory",
"Disable" : "Disabled",
"Disable Codecs" : "Disable Codecs",
"Disabled" : "Disabled",
"DispCode" : "DispCode",
"Display Called Party Information" : "Display Called Party Information",
"Display Contact Photo" : "Display Contact Photo",
"Display Method on Dialing" : "Display Method on Dialing",
"Display Name" : "Display Name",
"Display Report Options On Web" : "Display Report Options on Web",
"display_name" : "display_name",
"DisplayName" : "DisplayName",
"Diversion/History-Info" : "Diversion/History-Info",
"DND" : "DND",
"DND Active" : "DND Active",
"DND Status" : "DND Status",
"DND Sync for Shared Line" : "DND Sync for Shared Line",
"DNS Cache" : "DNS Cache",
"DNS NAPTR" : "DNS NAPTR",
"Do Not Disturb" : "Do Not Disturb",
"Do not support vlan in PPPoE mode!" : "Do not support VLAN in PPPoE mode!",
"Do you want to autoprovision now?" : "Do you want to autoprovision now?",
"Do you want to discard your changes ?" : "Do you want to discard your changes ?",
"Do you want to import the configuration file to All_Configuration" : "Do you want to import the configuration file to All_Configuration?",
"Do you want to import the configuration file to Local_Configuration" : "Do you want to import the configuration file to Local Configuration?",
"Do you want to import the configuration file?" : "Do you want to import the configuration file?",
"Do you want to reboot ?" : "Do you want to reboot ?",
"Do you want to reset to factory ?" : "Do you want to reset to factory ?",
"Door Phone Update Interval (0~300)" : "Door Phone Update Interval (0~300)",
"Down" : "Down",
"Download" : "Download",
"download customs, please try latter!" : "Download customs, please try again later!",
"Download failed!" : "Download failed!",
"Download failed, please try again" : "Download failed, please try again",
"Downloading custom list, please try latter!!" : "Downloading custom list, please try again later!",
"DPickup" : "DPickup",
"Draft BLA" : "Draft BLA",
"Driver" : "Driver",
"Dsskey" : "Dsskey",
"dsskey-ext-note" : "<B>Ext Keys</B><br/>Customize the key feature in the expansion module.<br/><br/>",
"dsskey-linekey-note" : "<B>Line Keys</B><br>Line keys allow you to quickly access features such as recall and voice mail.<br><br>",
"dsskey-note" : "<B>Key Type</B><br/>The free function key 'Types' Speed Dial, Key Event, Intercom.<br/><br/><b>Key Event</B><br/>Key events are predefined shortcuts to phone and call functions.<br/><br/><b>Intercom</B><br/>Enable the 'Intercom' mode and it is useful in an office environment as a quick access to connect to the operator or the secretary.<br/><br/>",
"dsskey-programkey-note" : "<B>Programmable Keys</B><br/>Customize the soft keys, navigation keys and function keys.<br/><br/>",
"DsskeyWallpaper" : "Dsskey Wallpaper",
"DST By Date" : "DST by Date",
"DST By Week" : "DST by Week",
"DTMF" : "DTMF",
"DTMF Info Type" : "DTMF Info Type",
"DTMF Payload Type" : "DTMF Payload Type (96~127)",
"DTMF Type" : "DTMF Type",
"DTMF-Relay" : "DTMF-Relay",
"EAP-FAST" : "EAP-FAST",
"EAP-MD5" : "EAP-MD5",
"EAP-None" : "EAP-None",
"EAP-PEAP/GTC" : "EAP-PEAP/GTC",
"EAP-PEAP/MSCHAPv2" : "EAP-PEAP/MSCHAPv2",
"EAP-TLS" : "EAP-TLS",
"EAP-TTLS/EAP-GTC" : "EAP-TTLS/EAP-GTC",
"EAP-TTLS/EAP-MSCHAPv2" : "EAP-TTLS/EAP-MSCHAPv2",
"ECHO" : "ECHO",
"Echo Cancellation" : "Echo Cancellation",
"Edit" : "Edit",
"Emergency" : "Emergency",
"Emergency should only contain digital number and ','!" : "Emergency number should only contain digit and ','",
"Empty" : "Empty",
"Enable" : "Enabled",
"Enable Auto Favorite" : "Enable Auto Favorite",
"Enable Codecs" : "Enable Codecs",
"Enable Custom Directories" : "Enable Custom Directory",
"Enable Direct Process" : "Enable Direct Process",
"Enable LDAP" : "Enable LDAP",
"Enable Local Log" : "Enable Local Log",
"Enable Outbound Proxy Server" : "Enable Outbound Proxy Server",
"Enable Periodic Inform" : "Enable Periodic Inform",
"Enable Signal Encode" : "Enable Signal Encode",
"Enable Syslog" : "Enable Syslog",
"Enable TR069" : "Enable TR069",
"enable via received" : "Enable via Received",
"Enabled" : "Enabled",
"Encryption Type" : "Encryption Type",
"End Call" : "End Call",
"End Call On Hook" : "End Call on Hook",
"End Date" : "End Date",
"EndSystemDelay" : "EndSystemDelay",
"English" : "English (English)",
"Enhanced" : "Enhanced",
"Enter at least 6 characters with 1 number and 1 alphabet min" : "Enter at least 6 characters including at least 1 digit and 1 letter!",
"Enterprise" : "Enterprise",
"Enterprise Phone Book" : "Enterprise Phone Book",
"EnterpriseCommon" : "EnterpriseCommon",
"Error: Element's name is empty!" : "Error: Element's name is empty!",
"Error: More than" : "Error: More than",
"Error: More than five groups." : "Error: More than five groups.",
"Error: Record with the same Prefix already exists!" : "Error: Record with the same Prefix already exists!",
"Error: Record with the same Rule already exists!" : "Error: Record with the same Rule already exists!",
"Error: Same config" : "Error: Same config",
"Error: The max replace rule count is" : "Error: The max number of replace rules is",
"Error: The maximum number of certificates is 10, please delete one before upload" : "Error: The maximum number of certificates is 10, please delete one before upload",
"Error: The password is error!" : "Error: The old password is incorrect!",
"Error: The same record already exists!" : "Error: The same record already exists!",
"Error:Contact already existed!" : "Error: Contact already exists!",
"Error:Dongle is not inserted!" : "Error: Dongle is not inserted!",
"Error:Group not existed!" : "Error: Group does not exist!",
"Error:Import config error!" : "Error: Import config error!",
"Error:Invalid file!" : "Error:Invalid file!",
"Error:The pin code is error!" : "Error: The PIN code is incorrect!",
"Established" : "Established",
"Exit" : "Exit",
"Exp Switch" : "EXP Switch",
"Expiration" : "Expiration",
"Export" : "Export",
"Export .csv file" : "Export .csv file",
"Export .xml file" : "Export .xml file",
"Export All Diagnostic Files" : "Export All Diagnostic Files",
"Export CFG Configuration File" : "Export CFG Configuration File",
"Export Contacts" : "Export Contacts",
"Export from" : "Export from",
"Export Import Config" : "Export or Import Configuration",
"Export Local Log" : "Export Local Log",
"Ext" : "Ext",
"FAC" : "FAC",
"Factory Installed" : "Factory Installed",
"Fail : Too many keys !" : "Error:Too many keys!",
"Fail to upload photo ! [Can not compress the picture]" : "Failed to upload photo! [The picture cannot be compressed]",
"Failed to connect to the server. Please check network connectivity." : "Failed to connect to the server. Please check network connection.",
"Failed to reset built-in SD card!" : "Failed to reset built-in SD card!",
"Failed to reset local settings!" : "Failed to reset local settings!",
"Failed to reset non-static settings" : "Failed to reset non-static settings",
"Failed to reset static settings!" : "Failed to reset static settings!",
"Failed to reset to factory!" : "Failed to reset to factory!",
"Failed to reset user data & local config!" : "Failed to reset user data & local config!",
"failReason" : "Fail Reason",
"Family.png" : "Family.png",
"FarHold" : "Far Hold",
"Favorite" : "Favorite",
"Favorite Index" : "Favorite Index",
"Feature Key Synchronization" : "Feature Key Synchronization",
"Feature_Key_Synchronisation" : "Feature Key Synchronization",
"Features" : "Features",
"features-acd-note" : "<b>Automatic Call Distribution (ACD) </b><br>It enables organizations to manage a large number of phone calls on an individual basis in a call center role by automatically distributing incoming calls to available users or agents.<br><br>ACD is disabled on the IP phone by default. You need to enable it on a per-line basis before logging into the ACD system.<br><br>ACD depends on a SIP server support.<br>",
"features-actionurl-note" : "<b>Action URL</b><br>It allows IP phones to interact with web server applications by sending an HTTP or HTTPS GET request. <br><br>You can specify a URL that triggers a GET request when a specified event occurs. Action URL can only be triggered by the pre-defined events (e.g., Incoming Call).<br><br>The valid URL format is: <I>http(s)://IP address of the server/help.xml?.<I><br>",
"features-audio-note" : "<b>Tone</b><br>It allows IP phone to play call waiting tone, key tone and send tone.<br><b>Ringer Device for Headset</b><br>Select speaker or/and headset as the ringer devices.<br>",
"features-bluetooth-note" : "<b> Bluetooth support </b> <br> The menu allows you to activate the USB port on your phone to connect the Bluetooth adapter for wireless headsets <br>",
"features-callpickup-note" : "<b>Directed Call Pickup</b><br>Pick up an incoming call on a specific extension.<br><br><b>Directed Call Pickup</b><br>Pick up incoming calls within a pre-defined group.<br><br>You can configure directed/group call pickup feature for the IP phone.<br>",
"features-doorphone-note" : "<b>Doorphone</b>",
"features-forward-note" : "<B>Call Forward</B><br>It allows users to redirect an incoming call to the third party.<br><br><b>Call Forward Mode</B><br><b>Phone: </b>Call forward feature is effective for the IP phone.<br><b>Custom: </b>Call forward feature is effective for the specific account.<br><br><b>Do Not Disturb (DND) </b><br>It allows IP phones to ignore incoming calls. <br><br><b>DND Mode</B><br><b>Phone: </b>DND feature is effective for the IP phone.<br><b>Custom: </b>DND feature is effective for the specific account.",
"features-general-note" : "<B>Call Waiting</B><br>It allows IP phones to receive a new incoming call when there is already an active call.<br>",
"features-intercom-note" : "<b>Intercom</b><br>It allows IP phone to establish an audio conversation directly.<br><br>IP phones can answer intercom calls automatically.<br>",
"features-notification-popups-note" : "<b>Notification-Popups</b><br>It allows the message to pop up when the IP phone misses a call, forwards an incoming call to other party or receives a new voice mail or a new text message.<br>",
"features-phonelock-note" : "<b>Phone Lock</b><br>It is used to lock the IP phone to prevent it from unauthorized use. Once the IP phone is locked, a user must enter the password to unlock it. <br><br>IP phones offer three types of phone lock: Menu Key, Function Keys and All Keys.<br><br>The IP phone will not be locked immediately once the phone lock type is configured.<br>",
"features-power-led-note" : "<b>Power LED Indicator</b><br>It indicates power status and phone status.<br>",
"features-remotecontrl-note" : "<b>Action URI</b><brFor security, IP phones cannot receive and handle HTTP/HTTPS GET requests by default. You need to specify the trusted IP address for action URI.<br><br>You can specify one or more trusted IP addresses on the IP phone, or allow the IP phone to receive and handle the URI from any IP address.<br>",
"features-sms-note" : "<b>Short Message Service (SMS)</b><br>Send a text message.<br>",
"features-transfer-note" : "<b>Call Transfer</b><br>The parameters are for administrator to specify call transfer behavior. Call transfer enables users to relocate an existing call to another party. IP phones support call transfer using the REFER method specified in RFC 3515 and offer three types of transfer.<br><br><b>Blind Transfer</b><br> Transfer a call directly without consulting first. Blind transfer is implemented by a simple REFER method without Replaces in the Refer-To header. <br><br><b>Semi-attended Transfer</b><br>Transfer a call after hearing the ringback tone. Semi-attended transfer is implemented by a REFER method with Replaces in the Refer-To header. <br><br><b>Attended Transfer</b><br>Transfer a call with prior consulting. Attended transfer is implemented by a REFER method with Replaces in the Refer-To header. <br>",
"Feb" : "Feb",
"February" : "February",
"File Template Download" : "File Template Download",
"File's format isn't .csv!" : "The file format is not .csv!",
"File's format isn't .xml!" : "The file format is not .xml!",
"Finland" : "Finland",
"Firmware updating ..." : "Firmware updating ...",
"Firmware Version" : "Firmware Version",
"First In Month" : "First Week",
"Fixed" : "Fixed",
"Fixed Type" : "Fixed Type",
"Flexible Auto Provision" : "Flexible Auto Provision",
"Flexible Interval Days" : "Flexible Interval Days",
"Flexible Time" : "Flexible Time",
"float" : "float",
"FON Attendant Transfer" : "FON Attendant Transfer",
"Forward" : "Forward",
"Forward Active" : "Forward Active",
"Forward&DND" : "Forward&DND",
"Fourth In Month" : "Fourth Week",
"France" : "France",
"French" : "Français (French(EU))",
"Fri" : "Fri",
"friday" : "Friday",
"Friend.png" : "Friend.png",
"FROM" : "FROM",
"FTP daemon" : "FTP Daemon",
"Full Contact Info" : "Full Contact Info",
"Fwd International" : "Fwd International",
"G722" : "G722",
"G722_1_24" : "G.722.1 (24kb/s)",
"G722_1c_24" : "G.722.1c (24kb/s)",
"G722_1c_32" : "G.722.1c (32kb/s)",
"G722_1c_48" : "G.722.1c (48kb/s)",
"G723" : "G723",
"G723_53" : "G723_53",
"G723_53 and G723_63 can not be applied simultaneously!" : "G723_53 and G723_63 cannot be applied simultaneously!",
"G723_63" : "G723_63",
"G726-16" : "G726-16",
"G726-24" : "G726-24",
"G726-32" : "G726-32",
"G726-40" : "G726-40",
"G729" : "G729",
"Gateway" : "Gateway",
"Gateway IP address is invalid!" : "Gateway IP address is invalid!",
"Gateway IPv6 address is invalid!" : "Gateway IPv6 address is invalid!",
"Genband Standalone AS" : "Genband Standalone AS",
"General" : "General",
"General Account" : "General Account",
"General Information" : "General Information",
"Genesys" : "Genesys",
"Genesys Advanced" : "Genesys Advanced",
"German" : "Deutsch (German)",
"Germany" : "Germany",
"Get Balance" : "Get Balance",
"Get Balance Link" : "Get Balance Link",
"Gigabit Color IP Phone SIP-T29G" : "Gigabit Color IP Phone SIP-T29G",
"Gigabit Color IP Phone SIP-T46G" : "Gigabit Color IP Phone SIP-T46G",
"Gigabit Color IP Phone SIP-T46S" : "Gigabit Color IP Phone SIP-T46S",
"Gigabit Color IP Phone SIP-T48G" : "Gigabit Color IP Phone SIP-T48G",
"Gigabit Color IP Phone SIP-T48S" : "Gigabit Color IP Phone SIP-T48S",
"Global Address Book" : "Global Address Book",
"Google Contacts" : "Google Contacts",
"GPark" : "GPark",
"GPickup" : "GPickup",
"Great Britain" : "Great Britain",
"Greece" : "Greece",
"Group" : "Group",
"Group Call Park" : "Group Call Park",
"Group Call Park Code" : "Group Call Park Code",
"Group Call Pickup" : "Group Call Pickup",
"Group Call Pickup Code" : "Group Call Pickup Code",
"Group Listening" : "Group Listening",
"Group Pick Up" : "Group Pick Up",
"GroupCommon" : "GroupCommon",
"Handfree" : "Handsfree",
"Handset 1" : "Handset 1",
"Handset 2" : "Handset 2",
"Handset 3" : "Handset 3",
"Handset 4" : "Handset 4",
"Handset 5" : "Handset 5",
"Handset 6" : "Handset 6",
"Handset 7" : "Handset 7",
"Handset 8" : "Handset 8",
"Handset Firmware updating ..." : "Handset Firmware Updating ...",
"Handset Name" : "Handset Name",
"Handset No." : "Handset No.",
"Handset Version" : "Handset Version",
"Handset&VoIP" : "Handset&VoIP",
"Hang Up Failed" : "Hang Up Failed",
"Hangup" : "Hangup",
"hangup failed" : "Hangup Failed",
"Hangup Success" : "Hang up Successfully",
"Hardware Version" : "Hardware Version",
"HD IP Conference Phone CP920" : "HD IP Conference Phone CP920",
"Headset" : "Headset",
"Held" : "Held",
"Held Tone Interval must be between 3~3600!" : "Held Tone Interval must be between 3~3600!",
"Hidden" : "Hidden",
"hidden-note" : "<b>Hidden</b>",
"High" : "High",
"History" : "History",
"HOLD" : "Hold",
"Hold Tone Interval must be between 3~3600!" : "Hold Tone Interval must be between 3~3600!",
"Host Server" : "Host Server",
"Hot Desking" : "Hot Desking",
"Hoteling" : "Hoteling",
"Hotline Number" : "Hotline Number",
"Hotline Number should be a number or IP address !" : "Hotline Number should be a number or an IP address!",
"Hour" : "Hour",
"Hour 12" : "Hour 12",
"Hour 24" : "Hour 24",
"HTTP" : "HTTP",
"HTTP Digest" : "HTTP Digest",
"HTTP Port (1~65535)" : "HTTP Port (1~65535)",
"HTTPS" : "HTTPS",
"HTTPS Port (1~65535)" : "HTTPS Port (1~65535)",
"Hungary" : "Hungary",
"ICE" : "ICE",
"icon_blacklist_b.png" : "Blocklist.png",
"icon_family_b.png" : "Family.png",
"icon_friend_b.png" : "Friend.png",
"Identity" : "Identity",
"ignore" : "Ignore",
"Ignore DND" : "Ignore DND",
"iLBC" : "iLBC",
"iLBC(15.2kbps) and iLBC(13.33kbps) can't be applied simultaneously!" : "iLBC (15.2kbps) and iLBC (13.33kbps) cannot be applied simultaneously!",
"iLBC_13_33kbps" : "iLBC (13.33kbps)",
"iLBC_15_2kbps" : "iLBC (15.2kbps) ",
"Illegal address!" : "Illegal address!",
"Illegal domain address!" : "Illegal domain address!",
"Illegal IP address!" : "Illegal IP address!",
"Illegal IPv4 address!" : "Illegal IPv4 address!",
"Illegal IPv6 address!" : "Illegal IPv6 address!",
"Illegal sub-network mask!" : "Illegal sub-network mask!",
"Illegal URL address!" : "Illegal URL address!",
"IME" : "IME",
"Import" : "Import",
"Import CFG Configuration File" : "Import CFG Configuration File",
"Import Contacts" : "Import Contacts",
"Import Factory Config" : "Import Factory Config",
"Import License" : "Import License",
"Import Server Certificates" : "Import Server Certificates",
"Import to" : "Import to",
"Import Trusted Certificates" : "Import Trusted Certificates",
"Inactivity Time Expire(0~120min)" : "Inactivity Time Expire (0~120min)",
"INBAND" : "INBAND",
"Incoming Call" : "Incoming call",
"Incoming lines" : "Incoming Lines",
"Incoming/Outgoing Call Lookup" : "Incoming/Outgoing Call Lookup",
"Index" : "Index",
"Index Id" : "Index Id",
"India" : "India",
"info" : "Info",
"Input contains invalid character like" : "The input contains invalid character like",
"Input contains invalid character like '< '" : "The input contains invalid characters like '< '",
"Input contains invalid character like '<>'" : "The input contains invalid characters like '<>'",
"Input contains invalid character like <>'\\\"" : "Input contains invalid characters like <>'\\\'",
"Install server certs error!" : "Install server certs error!",
"Installed failed" : "Install failed",
"InterarrivalJitter" : "Interarrival Jitter",
"Intercom" : "Intercom",
"Internal Ringer File" : "Internal Ringer File",
"Internal Ringer Text" : "Internal Ringer Text",
"Internet Port" : "Internet Port",
"Interval(Minutes)" : "Interval (Minutes)",
"Invail value." : "Invail Value!",
"Invaild Broadsoft XSI host addres !" : "Invalid Broadsoft XSI host address!",
"Invaild Primary NTP Server !" : "Invalid Primary NTP server!",
"Invaild Secondary NTP Server !" : "Invalid Secondary NTP server!",
"Invalid address!" : "Invalid address!",
"Invalid characters. Only digits and commas are allowed!" : "Invalid characters. Only digits and commas are allowed!",
"Invalid connection request username!" : "Invalid connection request username!",
"Invalid Day!" : "Invalid Day!",
"Invalid daylight saving end day!" : "Invalid daylight saving end day!",
"Invalid daylight saving start day!" : "Invalid daylight saving start day!",
"Invalid daylight saving start/end time !" : "Invalid daylight saving start/end time!",
"Invalid DHCP option!" : "Invalid DHCP option!",
"Invalid DTMF payload !" : "Invalid DTMF payload!",
"Invalid factory file!" : "Invalid factory file!",
"Invalid file name!" : "Invalid file name!",
"Invalid Max RTP Port !" : "Invalid Max RTP Port!",
"Invalid Min RTP Port !" : "Invalid Min RTP Port!",
"Invalid Number" : "Invalid Number",
"Invalid Number!" : "Invalid number!",
"Invalid password!" : "Invalid password!",
"Invalid port!" : "Invalid port!",
"Invalid prefix String !" : "Invalid prefix string!",
"Invalid request password!" : "Invalid connection request password!",
"Invalid ringer text string!" : "Invalid ringer text string!",
"Invalid server URL!" : "Invalid server URL!",
"Invalid SipQos" : "Invalid Sip QoS!",
"Invalid SNMP Port !" : "Invalid SNMP port!",
"Invalid SNMP Trused address !" : "Invalid SNMP Trusted address!",
"Invalid String" : "Invalid String",
"Invalid syslog server address !" : "Invalid syslog server address!",
"Invalid URL!" : "Invalid URL!",
"Invalid username!" : "Invalid username!",
"Invalid value!" : "Invalid value!",
"Invalid VID" : "Invalid VID!",
"Invalid VoiceQos" : "Invalid Voice QoS!",
"IP Address" : "IP Address",
"IPv4" : "IPv4",
"IPv4 & IPv6" : "IPv4 & IPv6",
"IPv4 Config" : "IPv4 Config",
"IPv4 Custom Option" : "IPv4 Custom Option",
"IPv4 DHCP Option Value" : "IPv4 DHCP Option Value",
"IPv6" : "IPv6",
"IPv6 Config" : "IPv6 Config",
"IPv6 Custom Option" : "IPv6 Custom Option",
"IPv6 prefix is invalid" : "IPv6 prefix is invalid!",
"IPv6 Prefix(0~128)" : "IPv6 Prefix (0~128)",
"IPv6 Static DNS" : "IPv6 Static DNS",
"Issued By" : "Issued by",
"Issued To" : "Issued to",
"It will take a few minutes to update the firmware. Please do not power off!" : "It will take a few minutes to update the firmware. Please do not power off!",
"Italian" : "Italiano (Italian)",
"Italy" : "Italy",
"Jan" : "Jan",
"January" : "January",
"Japan" : "Japan",
"Jitter" : "Jitter",
"JITTER BUFFER" : "Jitter Buffer",
"Jitter Buffer Max" : "Jitter Buffer Max",
"JitterBufferMax" : "Jitter Buffer Max",
"Join" : "Join",
"Jul" : "Jul",
"July" : "July",
"Jun" : "Jun",
"June" : "June",
"Keep Alive Interval" : "Keep Alive Interval (Seconds)",
"Keep Alive Type" : "Keep Alive Type",
"kernel messages" : "Kernel Messages",
"Key" : "Key",
"Key As Send" : "Key As Send",
"Keypad Lock" : "Phone Lock",
"KeypadLock" : "Phone Lock",
"l.deleteConfirmMsg" : "l.deleteConfirmMsg",
"l.deleteWarnMsg" : "l.deleteWarnMsg",
"Label" : "Label",
"LAN_IP_Address" : "LAN IP Address",
"Last In Month" : "Last Week",
"LDAP" : "LDAP",
"LDAP Display Name" : "LDAP Display Name",
"LDAP Label" : "LDAP Label",
"LDAP Lookup For Callout" : "LDAP Lookup for Callout",
"LDAP Lookup For Incoming Call" : "LDAP Lookup for Incoming Call",
"LDAP Name Attributes" : "LDAP Name Attributes",
"LDAP Name Filter" : "LDAP Name Filter",
"LDAP Number Attributes" : "LDAP Number Attributes",
"LDAP Number Filter" : "LDAP Number Filter",
"LDAP Sorting Results" : "LDAP Sorting Results",
"LDAP TLS Mode" : "LDAP TLS Mode",
"LDAP TLS Start" : "LDAP TLS Start",
"LDAPS" : "LDAPS",
"LED Off in Idle" : "LED off in Idle",
"Left" : "Left",
"License" : "License",
"License Installed" : "License Installed",
"line" : "Line",
"Line 1" : "Line 1",
"Line 10" : "Line 10",
"Line 11" : "Line 11",
"Line 12" : "Line 12",
"Line 13" : "Line 13",
"Line 14" : "Line 14",
"Line 15" : "Line 15",
"Line 16" : "Line 16",
"Line 2" : "Line 2",
"Line 3" : "Line 3",
"Line 4" : "Line 4",
"Line 5" : "Line 5",
"Line 6" : "Line 6",
"Line 7" : "Line 7",
"Line 8" : "Line 8",
"Line 9" : "Line 9",
"Line Active" : "Line Active",
"Line Key10-18" : "Line Key10-18",
"Line Key1-11" : "Line Key1-11",
"Line Key11-15" : "Line Key11-15",
"Line Key12-20" : "Line Key12-20",
"Line Key1-5" : "Line Key1-5",
"Line Key15-21" : "Line Key15-21",
"Line Key1-7" : "Line Key1-7",
"Line Key1-9" : "Line Key1-9",
"Line Key19-27" : "Line Key19-27",
"Line Key21-29" : "Line Key21-29",
"Line Key6-10" : "Line Key6-10",
"Line Key8-14" : "Line Key8-14",
"Line Name" : "Line Name",
"Line No.&Name" : "Line No.&Name",
"line printer subsystem" : "Line Printer Subsystem",
"Line Selection" : "Line Selection",
"Linekey length in short" : "Linekey length in short",
"Link Down" : "Link Down",
"Listening Address" : "Listening Address",
"ListeningPaging" : "Listening Paging",
"ListeningPagingHold" : "Listening Paging Hold",
"Lithuania" : "Lithuania",
"LLDP" : "LLDP",
"Load Fail" : "Load failed!",
"Load Failed" : "Load failed!",
"Load License File" : "Load License File",
"Load Server Certificates File" : "Load Server Certificates File",
"Load Trusted Certificates File" : "Load Trusted Certificates File",
"Loading, please waiting" : "Loading, please wait...",
"Loading, please waiting..." : "Loading, please wait...",
"Local Anonymous" : "Local Anonymous",
"Local Anonymous Rejection" : "Local Anonymous Rejection",
"Local codec" : "Local Codec",
"Local Conference" : "Local Conference",
"Local Contacts" : "Local Directory",
"Local Directory" : "Local Directory",
"Local Group" : "Local Group",
"Local IP" : "Local IP",
"Local Log" : "Local Log",
"Local Log Level" : "Local Log Level",
"Local Port" : "Local Port",
"Local RTP Port" : "Local RTP Port",
"Local Settings" : "Local Settings",
"Local SIP Port" : "Local SIP Port",
"Local SIP Port should be a number !!" : "Local SIP Port should be a number!",
"local use 0 (local0)" : "Local Use 0 (Local0)",
"local use 1 (local1)" : "Local Use 1 (Local1)",
"local use 2 (local2)" : "Local Use 2 (Local2)",
"local use 3 (local3)" : "Local Use 3 (Local3)",
"local use 4 (local4)" : "Local Use 4 (Local4)",
"local use 5 (local5)" : "Local Use 5 (Local5)",
"local use 6 (local6)" : "Local Use 6 (Local6)",
"local use 7 (local7)" : "Local Use 7 (Local7)",
"Local user" : "Local user",
"LocalMenu" : "Local Phonebook",
"Location" : "Location",
"Lock" : "Lock",
"log alert (note 1)" : "Log Alert (Note 1)",
"log audit (note 1)" : "Log Audit (Note 1)",
"Log Out" : "Log Out",
"Login" : "Login",
"Logon Wizard" : "Logon Wizard",
"Low" : "Low",
"MAC Address" : "MAC Address",
"Machine ID" : "Machine ID",
"MAC-Oriented AES Key" : "MAC-Oriented AES Key",
"mail system" : "Mail System",
"Manager" : "Manage",
"Manual" : "Manual",
"Manual NAT" : "Manual NAT",
"Manual Time" : "Manual Time",
"Mar" : "Mar",
"March" : "March",
"Max Delay" : "Max Delay",
"Max Delay is less than Min Delay !" : "Max Delay is less than Min Delay!",
"Max Hits (1~32000)" : "Max Hits (1~1000)",
"Max Length (1-15)" : "Max Length (1-15)",
"Max Log File Size" : "Max Log File Size (256-2048KB)",
"Max Number of Registered Handset" : "Max Number of Registered Handset",
"Max RTP Port (1024~65535)" : "Max RTP Port (1024~65535)",
"Max RTP Port is less than Min RTP Port!" : "Max RTP Port is less than Min RTP Port!",
"Max.Hits(1~1000)" : "Max.Hits (1~1000)",
"May" : "May",
"MD5 Password" : "MD5 Password",
"Meet-me" : "Meet-me",
"Meet-Me Conference" : "Meet-Me Conference",
"Menu" : "Menu",
"Message" : "Message",
"Message List" : "Message List",
"messages generated internally by syslogd" : "Messages are generated internally by syslog",
"Messages List" : "Messages List",
"Metaswitch Active" : "Metaswitch Active",
"Metaswitch Login Mode" : "Metaswitch Login Mode",
"Mexico" : "Mexico",
"Min Delay" : "Min Delay",
"Min Length (1-15)" : "Min Length (1-15)",
"Min RTP Port (1024~65535)" : "Min RTP Port (1024~65535)",
"Minute" : "Minute",
"MissCall Power Light Flash" : "MissCall Power Light Flash",
"MM DD WW" : "MM DD WW",
"MM DD WWW" : "MM DD WWW",
"MM/DD/YY" : "MM/DD/YY",
"Mobile Contacts" : "Mobile Contacts",
"mobile_number" : "Mobile Number",
"MobileNumber" : "Mobile Number",
"Mode" : "Mode",
"Mode(IPv4/IPv6)" : "Mode (IPv4/IPv6)",
"Module Log" : "Module Log",
"Module Log Level" : "Module Log Level",
"Mon" : "Mon",
"monday" : "Monday",
"Month" : "Month",
"MOS-CQ" : "MOS-CQ",
"MOS-LQ" : "MOS-LQ",
"Multicast Codec" : "Multicast Codec",
"Multicast IP" : "Multicast IP",
"Multicast Listening" : "Multicast Listening",
"Must enter digits!" : "Please enter digits!",
"Must enter numbers!" : "Please enter numbers!",
"MUTE" : "MUTE",
"MWI Subscription Period(Seconds)" : "MWI Subscription Period (Seconds)",
"My Status" : "My Status",
"N/A" : "N/A",
"Name" : "Name",
"Name & Number" : "Name & Number",
"Name+Number" : "Name+Number",
"NAT" : "NAT",
"Nat Manual" : "Manual NAT",
"Netherlands" : "Netherlands",
"Network" : "Network",
"Network Call List" : "Network Call List",
"Network Call Log" : "Network Call Log",
"Network Common" : "Network Common",
"Network Conference" : "Network Conference",
"Network Contacts" : "Network Contacts",
"Network Directories" : "Network Directory",
"Network Directory" : "Network Directory",
"Network Favorites" : "Network UC Favorites",
"Network Group" : "Network Group",
"network news subsystem" : "Network News Subsystem",
"network-adv-note" : "<b>Network Advanced Settings</b>",
"NetworkConferenced" : "Network Conference",
"NetworkConferencedHold" : "Network Conference Hold",
"network-diagnosis-note" : "<b>Network diagnosis</b><br>Troubleshoot network connectivity problems</br>",
"NetworkDirectoryGroup" : "Network Group",
"network-nat-note" : "<b>Network NAT Settings</b>",
"network-note" : "<b>DHCP</b><br>DHCP (Dynamic Host Configuration Protocol)is a network protocol used to dynamically allocate network parameters to IP phones.<br><br><b>Static IP Address</b><br><br>Specifies the network parameters of IP phones manually.<br><br><b>IPv6 Support</b><br><br>IPv6 is developed to deal with the long-anticipated problem of IPv4 address exhaustion.<br>",
"NetworkPacketLossRate" : "NetworkPacketLossRate",
"network-pcport-note" : "<b>PC Port Mode</b><br>The PC port on the back of the IP phone is used to connect a PC.<br><br>You can enable or disable the PC (LAN)port.",
"network-wifi-note" : "<b>Wi-Fi</b><br>Wi-Fi is a popular wireless networking technology that uses radio waves to provide wireless high-speed Internet and network connections. You can activate/deactivate the Wi-Fi mode on the IP phone, and then connect your phone to the desired wireless network.<br>",
"Never" : "Never",
"Never/Always/Adaptive" : "Never/Always/Adaptive",
"New Base PIN" : "New Base PIN",
"New Call" : "New Call",
"New Password" : "New Password",
"New password is similar to username, are you sure to set it?" : "New password is similar to username. Do you want to continue?",
"New password is too simple, are you sure to set it?" : "New password is too simple. Do you want to continue?",
"New Zealand" : "New Zealand",
"NewCall" : "NewCall",
"NewCallIn" : "NewCall in",
"NewSMS" : "New SMS",
"Next" : "Next",
"No Account" : "No Account",
"No Answer Forward" : "No Answer Forward",
"No data to import" : "No data to import",
"No selected file" : "No selected file",
"NONE" : "None",
"Non-static Settings" : "Non-static Settings",
"Normal" : "Normal",
"Normal Delay is beyond scope !" : "Normal Delay is beyond scope!",
"Norway" : "Norway",
"NOTE" : "NOTE",
"Notify" : "Notify",
"Nov" : "Nov",
"November" : "November",
"NTP By DHCP Priority" : "NTP by DHCP Priority",
"NTP subsystem" : "NTP Subsystem",
"Null" : "Null",
"num" : "Num",
"Number" : "Number",
"Number Assignment" : "Number Assignment",
"Number of line key" : "Number Of Line Key",
"Number of simultaneous outgoing calls" : "Simultaneous Outgoing Call Capacity",
"Number+Name" : "Number+Name",
"Oct" : "Oct",
"October" : "October",
"OFF" : "OFF",
"Off Code" : "Off Code",
"Off Code could not be empty when On Code is set!" : "Off code cannot be empty when on code is set!",
"office_number" : "Office Number",
"OfficeNumber" : "Office Number",
"Offset(minutes)" : "Offset (minutes)",
"OK" : "OK",
"Old group name is empty!" : "Old group name is empty!",
"Old Password" : "Old Password",
"ON" : "ON",
"On Code" : "On Code",
"On Hook" : "On Hook",
"Only Accept Trusted Certificates" : "Only Accept Trusted Certificates",
"Only One of these Codecs can be enabled :" : "Only one of these codecs can be enabled :",
"Operate Failed" : "Operate Failed",
"Operate Success" : "Operate Successfully",
"Operating has done!" : "Operation completed!",
"Operating, please Wait ..." : "Operations are in progress, please wait...",
"operInfo" : "Operation Info",
"Option" : "Option",
"Option (1-255)" : "Option (1-255)",
"Optional" : "Optional",
"Options" : "Options",
"opus" : "Opus",
"Opus Sample Rate" : "Opus Sample Rate",
"Opus-FB(48KHz)" : "Opus-FB (48KHz)",
"Opus-MB(12KHz)" : "Opus-MB (12KHz)",
"Opus-NB(8KHz)" : "Opus-NB (8KHz)",
"Opus-SWB(24KHz)" : "Opus-SWB (24KHz)",
"Opus-WB(16KHz)" : "Opus-WB (16KHz)",
"OS" : "OS(operating system)",
"other_number" : "Other Number",
"Outbound Proxy Server 1" : "Outbound Proxy Server 1",
"Outbound Proxy Server 2" : "Outbound Proxy Server 2",
"OutboundPort should be a number !!" : "OutboundPort should be a number!",
"Outgoing Call" : "Outgoing Call",
"Outgoing lines" : "Outgoing lines",
"Packet Interval (1~3600s)" : "Packet Interval (1~3600s)",
"Packets Lost" : "Packets Lost",
"Page" : "Page",
"Paging" : "Multicast Paging",
"Paging Address" : "Paging Address",
"Paging Barge" : "Paging Barge",
"Paging List" : "Paging List",
"Paging Priority Active" : "Paging Priority Active",
"Paging Status" : "Paging Status",
"PagingHold" : "Paging Hold",
"PAI" : "PAI",
"PAI-FROM" : "PAI-FROM",
"PAI-RPID-FROM" : "PAI-RPID-FROM",
"Park" : "Park",
"Park Retrieve Code" : "Park Retrieve Code",
"Password" : "Password",
"Password is too simple, are you sure to set it?" : "Password is too simple, are you sure to set it?",
"Passwords don't match!" : "Passwords don't match!",
"Pcap Feature" : "Pcap Feature",
"Pcap Type" : "Pcap Type",
"PCMA" : "PCMA",
"PCMU" : "PCMU",
"pcport_active" : "PC Port Active",
"Period for Interval Report" : "Period for Interval Report",
"Periodic Inform Interval (seconds)" : "Periodic Inform Interval (seconds)",
"Persistent flag" : "Permanent Flag",
"Personal" : "Personal",
"Personal Address Book" : "Personal Address Book",
"Phone" : "Phone",
"Phone Lock" : "Phone Lock",
"Phone Setting" : "Phone Setting",
"PhoneBook" : "Phonebook",
"Photo" : "Photo",
"Pick Up" : "Pick Up",
"Pick up & Park" : "Call Park",
"Ping" : "Ping",
"PINs are not changed !" : "PINs are not changed!",
"Pins can't be less than 4!" : "PIN cannot be less than 4 digits!",
"Pins don't match!" : "PINs do not match!",
"Play Held Tone Delay must be between 3~3600!" : "Play Held Tone Delay must be between 3~3600!",
"Play Hold Tone Delay must be between 3~3600!" : "Play Hold Tone Delay should be between 3~3600!",
"Please choose at least one record!" : "Please choose at least one record!",
"Please choose the DisplayName" : "Please choose the DisplayName",
"Please click Confirm to load custom directories." : "Please click Confirm to load custom directories.",
"Please enable a codec at least!" : "Please enable one codec at least!",
"Please input complete information!" : "Please input complete information!",
"Please register your handset..." : "Please register your handset...",
"Please select a .cfg format file at first!" : "Please select a .cfg file at first!",
"Please select a .png or .jpg or .bmp  format file at first!" : "Please select a file in .png, .jpg or .bmp format first!",
"Please select a .wav format file at first!" : "Please select a .wav file at first!",
"Please select a correct file(.bin)." : "Please select a correct .bin file.",
"Please select a correct file(.cfg)." : "Please select a correct .cfg file.",
"Please select a file" : "Please select a file",
"Please select a file in correct format: .csv" : "Please select a file in correct format: .csv",
"Please select a file in correct format: .png,.jpg,.jpeg,.bmp" : "Please select a file in correct format: .png,.jpg,.jpeg,.bmp",
"Please select a file in correct format: .xml" : "Please select a file in correct format: .xml",
"Please select a file." : "Please select a file.",
"Please select a group!" : "Please select a group!",
"Please select one cert at least." : "Please select one cert at least.",
"Please select the contacts list file." : "Please select the contacts list file.",
"Please select the item which you want to edit!" : "Please select the item you want to edit!",
"Please select the record which you want to edit." : "Please select the record which you want to edit.",
"Please specify the blockout number!" : "Please specify the blockout number!",
"Please upload VPN config file first!" : "Please upload VPN config file first!",
"please wait ..." : "Please wait...",
"Please wait and do not power off!" : "Please wait and do not power off!",
"PM" : "PM",
"PNP Active" : "PNP Active",
"Polish" : "Polski (Polish)",
"Port" : "Port",
"Portugal" : "Portugal",
"Portuguese" : "Português (Portuguese(EU))",
"Power LED" : "Power LED",
"Power On" : "Power On",
"PPPoE" : "PPPoE",
"precondition" : "Precondition",
"PREFERENCE" : "Preference",
"Preference(IPv4/IPv6)" : "Preference (IPv4/IPv6)",
"Prefix" : "Prefix",
"Prefix and Replace should not be Empty !" : "Prefix and Replace cannot be Empty!",
"Presence List" : "Presence List",
"Prev" : "Prev",
"Preview" : "Preview",
"PriHold" : "PriHold",
"Primary DNS" : "Primary DNS",
"Primary DNS error, please check" : " Primary DNS is incorrect, please check!",
"Primary Server" : "Primary Server",
"Priority" : "Priority",
"Private Hold" : "Private Hold",
"Profile Name" : "Profile Name",
"Protocol" : "Protocol",
"Provisioning Mode" : "Provisioning Mode",
"Proxy Fallback Interval" : "Proxy Fallback Interval",
"Proxy Require" : "Proxy Require",
"Proxy require can not contain ! and &." : "Proxy Require cannot contain! and &.",
"PSTN1" : "PSTN1",
"PSTN2" : "PSTN2",
"PSW Dial Length Invalid !" : "Invalid PSW Dial Length!",
"PTime(ms)" : "PTime (ms)",
"PTT" : "Prefix",
"Push XML" : "Push XML",
"Push XML failed!" : "Push XML failed!",
"PushXML Test" : "PushXML Test",
"QoS" : "QOS",
"RC4" : "RC4",
"Reboot" : "Reboot",
"Reboot In Talking" : "Reboot in Talking",
"Rebooting, please wait ..." : "Rebooting, please wait...",
"ReCall" : "Recall",
"Recent Call In Dialing" : "Recent Call In Dialing",
"Record" : "Record",
"Redial" : "Redial",
"ReDialtone number should be a number !" : "ReDialtone number should be a number!",
"Redirect Active" : "Redirect Active",
"Refresh" : "Refresh",
"Registed Full!" : "Registration has reached the max limit!",
"Register" : "Register",
"Register Failed" : "Register Failed",
"Register Name" : "Register Name",
"Register Status" : "Register status",
"Registered" : "Registered",
"Registered Handsets" : "Registered Handsets",
"Registering" : "Registering",
"Registration Random" : "Registration Random",
"Registration Random (0~60s)" : "Random Registration (0~60s)",
"Reject" : "Reject",
"Remote Codec" : "Remote Codec",
"Remote Control" : "Remote Control",
"Remote IP" : "Remote IP",
"Remote Pcap" : "Remote Pcap",
"Remote Pcap Password" : "Remote Pcap Password",
"Remote Pcap Port" : "Remote Pcap Port",
"Remote Phone Book" : "Remote Phone Book",
"Remote Phonebook" : "Remote Phonebook",
"Remote Port" : "Remote Port",
"Remote URL" : "Remote URL",
"Remote User" : "Remote User",
"Remote_Pcap_Switch" : "Remote Pcap Switch",
"Remove" : "Remove",
"Repeatedly" : "Repeatedly",
"Replace" : "Replace",
"Replace Rule" : "Replace Rule",
"ReportIP" : "Report IP",
"Reserve # in User Name" : "Reserve # in Username",
"Reserved Character in User Name" : "Reserved Character in Username",
"Reset" : "Reset",
"Reset built-in SD card successfully!" : "Reset built-in SD card successfully!",
"Reset Local Settings" : "Reset local settings",
"Reset local settings successfully!" : "Reset local settings successfully!",
"Reset Non-static Settings" : "Reset non-static settings",
"Reset non-static settings successfully!" : "Reset non-static settings successfully!",
"Reset SoftKey" : "Reset Softkey",
"Reset Static Settings" : "Reset static settings",
"Reset static settings successfully!" : "Reset static settings successfully!",
"Reset To Factory" : "Reset to Factory Settings",
"Reset to factory successfully!" : "Reset to factory successfully!",
"Reset user data & local config successfully!" : "Reset user data & local config successfully!",
"Reset Userdata & Local Config" : "Reset userdata & local config",
"Reset web settings" : "Reset web settings",
"Resume" : "Resume",
"Retransmission" : "Retransmission",
"Retrieve" : "Retrieve",
"Retrieve Park" : "Retrieve Park",
"Return Code When DND" : "Return Code When DND",
"Return Code When No Answer" : "Return Code When No Answer",
"Return Code When Refuse" : "Return Code When Refuse",
"RFC 2543 Hold" : "RFC 2543 Hold",
"RFC2833" : "RFC2833",
"RFC2833+SIP INFO" : "RFC2833+SIP INFO",
"Right" : "Right",
"ring" : "Ring",
"Ring Back" : "Ring Back",
"Ring Type" : "Ring Type",
"Ring Type for BLF Pickup" : "Ring Type for BLF Pickup",
"Ring1.wav" : "Ring1.wav",
"Ring2.wav" : "Ring2.wav",
"Ring3.wav" : "Ring3.wav",
"Ring4.wav" : "Ring4.wav",
"Ring5.wav" : "Ring5.wav",
"Ring6.wav" : "Ring6.wav",
"Ring7.wav" : "Ring7.wav",
"Ring8.wav" : "Ring8.wav",
"Ringer Device For Headset" : "Ringer Device for Headset",
"Ringing Power Light Flash" : "Ringing Power Light Flash",
"RoundTripDelay" : "RoundTripDelay",
"Router" : "Router",
"RPID-FROM" : "RPID-FROM",
"RPID-PAI-FROM" : "RPID-PAI-FROM",
"RPort" : "RPort",
"RTP Encryption(SRTP)" : "RTP Encryption (SRTP)",
"RTP Status" : "RTP Status",
"rtpstatus-note" : "RTP Status Note",
"Rule" : "Rule",
"Running" : "Running",
"Russia" : "Russia",
"Russian" : "Pусский (Russian)",
"Sat" : "Sat",
"saturday" : "Saturday",
"Save Call Log" : "Save Call Log",
"Screensaver" : "Screensaver",
"Search Source List In Dialing" : "Search Source List In Dialing",
"Second" : "Second",
"Second In Month" : "Second Week",
"Secondary DNS" : "Secondary DNS",
"Secondary DNS error, please check" : "Secondary DNS is incorrect, please check!",
"Secondary Server" : "Secondary Server",
"Security" : "Security",
"security/authorization messages (note 1)" : "Security/Authorization Messages (Note 1)",
"security-base-pin-note" : "<b>Base Unit PIN</b>",
"security-note" : "<b>User Password/ Administrator Password</b><br>When logging into the web user interface, you need to enter the username and password.<br><br>You can change the user/ administrator password for security.",
"Select .csv file form" : "Select .csv file form",
"Select .xml file form" : "Select .xml file form",
"Select And Upgrade Firmware" : "Select And Upgrade Firmware",
"Select and Upgrade Handset Firmware" : "Select and update handset firmware.",
"Select Country" : "Select Country",
"Semi-Attended Transfer" : "Semi-Attended Transfer",
"Send" : "Send",
"Send Anonymous Code" : "Send Anonymous Code",
"Send Anonymous Rejection Code" : "Send Anonymous Rejection Code",
"Send User=Phone" : "Send user=phone",
"Sep" : "Sep",
"September" : "September",
"Server Address" : "Server Address",
"Server Certificates" : "Server Certificates",
"Server Expires" : "Server Expires",
"Server Host" : "Server Host",
"Server Retry Counts" : "Server Retry Counts",
"Server URL" : "Server URL",
"server-cert-note" : "<b>Transport Layer Security (TLS) </b><b>Server Certificates</b><br>When clients request a TLS connection with the IP phone, the IP phone sends the server certificate to the clients for authentication. The IP phone has two types of built-in server certificates: a unique server certificate and a generic server certificate. You can only upload one server certificate to the IP phone. The old server certificate will be overridden by the new one. The format of the server certificate files must be *.pem and *.cer and the maximum file size is 5MB.<br><br><b>A unique server certificate:</b>It is unique to an IP phone (based on the MAC address) and issued by the Yealink Certificate Authority (CA).<br><br><b>A generic server certificate:</b> It is issued by the Yealink Certificate Authority (CA). Only if there is no unique certificate exists, may the IP phone send a generic certificate for authentication.<br>",
"Service" : "Service",
"Session Expires" : "Session Expires (90~7200s)",
"Session Refresher" : "Session Refresher",
"Session Timer" : "Session Timer",
"Setting" : "Settings",
"Settings" : "Settings",
"settings-autop-note" : "<b>Auto Provision</b><br>Begin time should be earlier than end time!<br><br>When the IP phone is triggered to perform auto provisioning, it will request to download the configuration files from the provisioning server. During the auto provisioning, the IP phone will download and update configuration files to the phone flash.<br>",
"settings-calldisplay-note" : "<b>Call Display</b><br>Display called party information allows the IP phone to present both the callee and caller ID information when it receives an incoming call.<br>",
"settings-config-note" : "<b>Configuration</b><br>IP phones can provide feedback in a variety of forms such as log files, packets, status indicators and so on, which can help an administrator more easily find the system problem and fix it.<br><br>· Log Files<br>· Capturing Packets<br>· Configuration File <br> (*.cfg/*.bin)<br><br>The *.bin file you export may contain some your personal data, including contacts, history records, web-side login information, etc. If you do not want to export this information, please clear them first on the phone.<br>",
"settings-datetime-note" : "<b>Time and Date</b><br>It displays on the idle screen of IP phones.<br><br><b>Time Zone</b><br>A time zone is a region on Earth that has a uniform standard time. It is convenient for areas in close commercial or other communication to keep the same time. <br><br><b>NTP Server</b><br>The IP phones synchronize the time and date automatically from the NTP time server by default.<br><br><b>Daylight Saving Time</b><br>It is the practice of temporary advancing clocks during the summer time so that evenings have more daylight and mornings have less. Typically, clocks are adjusted forward one hour at the start of spring and backward in autumn. <br>",
"settings-dialplan-note" : "<b>Replace Rule:</b>An alternative string that replaces the entered numbers.<br><b>Dial-now:</b>Automatically dial out the entered numbers.<br><b>Area Code:</b>Automatically add the area code before the numbers when dialing. <br><b>Block Out:</b>It prevents users from dialing out specific numbers.<br><br><b>'.':</b>represents any string.<br><b>'x':</b>represents any character. <br><b>'-':</b>match a range of characters within the brackets.<br><b>',':</b>a separator within the bracket.<br><b>'[]':</b>a character matches any of character sets.<br><b>'()':</b>combines two or more patterns.<br><b>'$':</b>followed by the sequence number of a parenthesis where the characters are placed in the parenthesis.<br>",
"settings-powersaving-note" : "<b>Settings Powersaving</b><br>The power saving feature is used to turn off the backlight and screen to conserve energy. The IP phone enters power-saving mode after it has been idle for a certain period of time.<br>",
"settings-preference-note" : "<b>Watch Dog</b>",
"settings-ring-note" : "<b>Distinctive Ring Tones</b<br>It allows you to apply a distinctive ring tone to a type of call.<br><br>The IP phone inspects the INVITE request for an \'Alert-Info\' header when receiving an incoming call.<br><br>If the INVITE request contains an \'Alert-Info\' header, the IP phone strips out the URL or keyword parameter and maps it to the appropriate ring tone.<br>",
"settings-sip-note" : "<b>SIP Session Timers</b><br>SIP session timers T1, T2 and T4 are SIP transaction layer timers defined in RFC 3261. <br><br>Timer T1 is an estimate of the Round Trip Time (RTT) of transactions between a SIP client and SIP server.<br><br>Timer T2 represents the maximum retransmitting time of any SIP request message.<br><br>Timer T4 represents the time the network will take to clear messages between the SIP client and server.<br>",
"settings-softkey-note" : "<b>Softkey Layout</b><br>It is used to customize the soft keys displaying at the bottom of the LCD screen.<br><br>You  configure the softkey layout using the softkey layout templates for different call states.<br>",
"settings-tones-note" : "<b>Tones</b><br>You can customize tones or select specialized tone sets (vary from country to country) to indicate different phone statuses.<br>",
"settings-tr069-note" : "<b>TR-069 Device Management</b><br>TR-069 is a technical specification defined by the Broadband Forum, which defines a mechanism that encompasses secure auto-configuration of a CPE (Customer-Premises Equipment), and incorporates other CPE management functions into a common framework.<br>",
"settings-upgrade-note" : "<b>Reset to Factory Setting</b><br>Resets the IP phone to factory configurations.<br><br><b>Reboot</b><br>Reboots the IP phone.<br><br><b>Upgrading Firmware</b><br>Upgrades firmware manually.",
"settings-voicemonitoring-note" : "<b>Voice Quality Monitoring</b><br>It allows the IP phones to generate various quality metrics for voice quality.<br><br>The VQ-RTCPXR mechanism, complaint with RFC 6035, sends the service quality metric reports contained in SIP PUBLISH messages to the central report collector.<br>",
"settings-voice-note" : "<b>Voice Activity Detection (VAD) </b><br>It is used in speech processing to detect the presence or absence of human speech.<br><br><b>Comfort Noise Generation (CNG) </b><br>It is used to generate synthetic background noise for voice communications to fill the artificial silence.<br><br><b>Jitter Buffer</b><br>It is a shared data area where voice packets can be collected, stored, and sent to the voice processor in even intervals.<br>",
"Shared Call Appearance" : "Shared Call Appearance",
"Shared Line" : "Shared Line",
"Short" : "Short",
"Should not contain other characters except" : "Cannot contain other characters except",
"Show Title" : "Show Title",
"Silence" : "Silence",
"Silent.wav" : "Silent.wav",
"SIP" : "SIP",
"SIP Config" : "SIP Config",
"SIP INFO" : "SIP INFO",
"SIP Notify" : "SIP Notify",
"SIP QoS (0~63)" : "SIP QoS (0~63)",
"SIP register retry timer should be a digit!" : "SIP register retry timer should be a number!",
"SIP Registration Retry Timer" : "SIP Registration Retry Timer (0~1800s)",
"SIP Send Line" : "SIP Send Line",
"SIP Send MAC" : "SIP Send MAC",
"SIP Server 1" : "SIP Server 1",
"SIP Server 2" : "SIP Server 2",
"sip server port should be a number !!" : "SIP server port should be a number!",
"SIP Server Type" : "SIP Server Type",
"SIP Session Timer T1" : "SIP Session Timer T1 (0.5~10s)",
"SIP Session Timer T2" : "SIP Session Timer T2 (2~40s)",
"SIP Session Timer T4" : "SIP Session Timer T4 (2.5~60s)",
"SIP_Qos can not be empty." : "SIP Qos cannot be empty!",
"SMS" : "SMS",
"SNMP" : "SNMP",
"Software_Version" : "Software Version",
"Spain" : "Spain",
"Spanish" : "Español (Spanish(EU))",
"SpeedDial" : "SpeedDial",
"Splash.wav" : "Splash.wav",
"Split" : "Split",
"SplitAll" : "Split All",
"Star2Star" : "Star2Star",
"Start" : "Start",
"Start Date" : "Start Date",
"Start Paging" : "Start Paging",
"Start Registration" : "Start Registration",
"Start Time" : "Start Time",
"Static DNS" : "Static DNS",
"Static IP" : "Static IP",
"Static IP Address" : "Static IP Address",
"Static Settings" : "Static Settings",
"Status" : "Status",
"status-note" : "<b>Version</b><br>It shows the firmware version and hardware version.<br><br><b>Network</b><br>It shows the network settings of Internet (WAN) port.<br><br><b>Account</b><br>It shows the registration status of SIP accounts.<br>",
"status-voip-note" : "<b>Handset&VoIP</b>",
"status-wifi-note" : "<b>Wi-Fi Status</b><br>Describe the Wi-Fi usage status</br>",
"Stop" : "Stop",
"Stop Paging" : "Stop Paging",
"Stop Registration" : "Stop Registration",
"Stop Time" : "Stop Time",
"STUN" : "STUN",
"STUN Port" : "STUN Port",
"STUN Port (1024~65000)" : "STUN Port (1024~65535)",
"STUN Server" : "STUN Server",
"Stutter" : "Stutter",
"Subnet Mask" : "Subnet Mask",
"Subnet mask address is invalid!" : "Subnet mask address is invalid!",
"Subscribe For MWI" : "Subscribe for MWI",
"Subscribe MWI To Voice Mail" : "Subscribe MWI to Voice Mail",
"Subscribe Period(Seconds)" : "Subscription Period (Seconds)",
"Subscribe Register" : "Subscribe Register",
"Subscription Period should be a number !!" : "Subscription period should be a number!",
"Sun" : "Sun",
"sunday" : "Sunday",
"Suppress DTMF Display" : "Suppress DTMF Display",
"Suppress DTMF Display Delay" : "Suppress DTMF Display Delay",
"SWAP" : "Swap",
"Sweden" : "Sweden",
"Switch" : "Switch",
"Switch Language, Please Wait ..." : "Setting language, please wait...",
"SwitchAccountDown" : "SwitchAccountDown",
"SwitchAccountUp" : "SwitchAccountUp",
"Switzerland" : "Switzerland",
"SymmOneWayDelay" : "SymmOneWayDelay",
"sys.log" : "sys.log",
"Syslog" : "Syslog",
"Syslog Facility" : "Syslog Facility",
"Syslog Level" : "Syslog Level",
"Syslog Prepend MAC" : "Syslog Prepend MAC",
"Syslog Server" : "Syslog Server",
"Syslog Transport Type" : "Syslog Transport Type",
"System" : "System",
"system daemons" : "System Daemons",
"System Logo" : "System Logo",
"Talk" : "Talking",
"Talking" : "Talking",
"Talking, please save config later." : "Talking, please save config later.",
"Talking, Please wait..." : "Talking, please wait...",
"Target" : "Target",
"TCP" : "TCP",
"Telephone-Event" : "Telephone-Event",
"TelMode" : "Tel Mode",
"Terminated" : "Terminated",
"text" : "text",
"Text_Logo" : "Text Logo",
"The Block Out Number should not contain other characters except digital number" : "The Block Out Number should not contain other characters except digital number",
"The Block Out Number should not contain other characters except digital number, '*', '[', ']', '-', ',', '.', 'x', ')', '(', ''." : "The Block Out Number should not contain other characters except digital number, '*', '[', ']', '-', ',', '.', 'x', ')', '(', ''.",
"The Block Out Number should not contain other characters except digital number, '*', '[', ']', '-', ',', '.', 'x', ')', '(', '\"'." : "The Block Out Number should not contain other characters except digital number, '*', '[', ']', '-', ',', '.', 'x', ')', '(', '\''.",
"The cert file has existed!" : "The cert file already exists!",
"The cert file has prefabricated!" : "The cert file is prefabricated!",
"The configuration information is not complete!" : "The configuration information is not complete!",
"The count of DHCP Option's values can't more than 5!" : "The value of DHCP Option should be less than 5!",
"The diagonsis, please reproduce the problem." : "Diagnose by packet capture, please reproduce the failure.",
"The file already exited !" : "File already exists!",
"The file format must be .csv!" : "The file format must be .csv!",
"The file format must be .dat!" : "The file format must be .dat!",
"The file format must be .dob!" : "The file format must be .dob!",
"The file format must be .pem , .crt , .cer or .der !" : "The file format must be .pem, .crt, .cer or .der!",
"The file format must be .pem , .crt , .cer or .der!" : "The file format must be .pem, .crt, .cer or .der!",
"The file format must be .pem or .cer!" : "The file format must be .pem or .cer!",
"The file format must be .pem!" : "The file format must be .pem!",
"The file format must be .rom!" : "The file format must be .rom!",
"The file format must be .tar!" : "The file format must be .tar!",
"The file format must be .xml!" : "The file format must be .xml!",
"The file name is too long!" : "The file name is too long!",
"The first line as the title" : "The first line as the title",
"The http port of webserver is invalid number!" : "Invalid HTTP Port of Web Server!",
"The https port of webserver is invalid number!" : "Invalid HTTPS Port of Web Server!",
"The length of value must be between" : "The length of value must be between",
"The length of value must be greater than" : "The length of value must be greater than",
"The length of value must be less than" : "The length of value must be less than",
"The license has existed!" : "The license already exists!",
"The Max Length must not be less than Min Length" : "The Max Length cannot be less than Min Length!",
"The operation is done!" : "Operation completed!",
"The original contact will be covered, continue?" : "The original contact will be covered, continue?",
"The password have invalid value!" : "The password contains invalid character!",
"The Secondary DNS is same as Primary DNS, please enter again" : "The Secondary DNS is same as Primary DNS, please enter again.",
"The SMS is empty !" : "The SMS is empty!",
"The STUN Server is empty!" : "The STUN Server is empty!",
"The TimeOffset value should be from -300 to +300!" : "The time offset value should be from -300 to +300!",
"The TURN Server is empty!" : "The TURN Server is empty!",
"The username can not be empty." : "The username cannot be empty.",
"The Username is empty!" : "The Username is empty!",
"The username or password is error!" : "Incorrect username or password!",
"The value must be 0 or a number between 1024 and 6553." : "The value must be 0 or a number between 1024 and 6553.",
"The value must be between" : "The value must be between",
"The value must be greater than" : "The value must be greater than",
"The value must be in" : "The value must be in",
"The value must be less than" : "The value must be less than",
"The value of (Local SIP Port) and (TLS SIP Port) can't be the same!" : "The value of Local SIP Port and TLS SIP Port cannot be same!",
"There is no such groups" : "The group does not exist!",
"Third In Month" : "Third Week",
"Thu" : "Thu",
"thursday" : "Thursday",
"Time" : "Time",
"Time & Date" : "Time & Date",
"Time Format" : "Time Format",
"Time Out for Dial Now Rule" : "Time Out for Dial Now Rule",
"Time Zone" : "Time Zone",
"Time&Date" : "Time&Date",
"TKIP AES" : "TKIP AES",
"TLS" : "TLS",
"TLS SIP Port" : "TLS SIP Port",
"Tones" : "Tones",
"Total" : "Total",
"TR069" : "TR069",
"Traceroute" : "Traceroute",
"TRAN" : "TRAN",
"Tranfer" : "Transfer",
"Transfer" : "Transfer",
"Transfer Mode Via Dsskey" : "Transfer Mode via Dsskey",
"Transparency" : "Transparency",
"Transport" : "Transport",
"Trusted Certificates" : "Trusted Certificates",
"trusted-cert-note" : "<b>Transport Layer Security (TLS) </b><br><b>Trusted Certificate</b><br>When the IP phone requests a TLS connection with a server, the IP phone should verify the certificate sent by the server to decide whether it is trusted based on the trusted certificates list. The IP phone has 30 built-in trusted certificates. You can upload 10 custom certificates at most. The format of the trusted certificate files must be *.pem,*.cer,*.crt and *.der and the maximum file size is 5MB.<br>",
"Tue" : "Tue",
"tuesday" : "Tuesday",
"Turkish" : "Türkçe (Turkish)",
"TURN" : "TURN",
"TURN Port (1~65535)" : "TURN Port (1024~65535)",
"TURN Server" : "TURN Server",
"TurstedAddr" : "TurstedAddr",
"Two or more items have been chosen!" : "Two or more items have been chosen!",
"Two or more records have been chosen!" : "Two or more records have been chosen!",
"txt" : "TXT",
"Type" : "Type",
"Type can not be \"BLF List\" when autoBlflist is on!" : "Type cannot be \'BLF List\' when autoBlflist is on!",
"Type can not be \"Line\" when AutoLinekeys is on!" : "Type cannot be \'Line\' when AutoLinekeys is on!",
"Type can not be \"Mobile Account\" when mobile doesn\'t connect successfully!" : "Type cannot be \'Mobile Account\' when mobile isn\'t connected successfully!",
"Type can not be \"Speed Dial\" when FavoriteDirAutoSetSwitch is on!" : "Type cannot be \'Speed Dial\' when auto Favorite Directory is enabled!",
"Type can not be \"UC Favourite\" when AutoFavorite is on!" : "Type cannot be \'UC Favourite\' when AutoFavorite is on!",
"Type cannot be \"Speed Dial\" when auto Favorite Directory is enabled!" : "Type cannot be \'Speed Dial\' when auto Favorite Directory is enabled!",
"UAC" : "UAC",
"UAS" : "UAS",
"UC" : "UC",
"UC Active" : "UC Active",
"UC Favorite" : "UC Favorite",
"UC Password" : "UC Password",
"UC Username" : "UC Username",
"UCServer" : "UC Server",
"UDP" : "UDP",
"UDP_Keep_alive_Interval should be a number !!" : "UDP keep alive interval should be a number!",
"Unauthenticated Provisioning" : "Unauthenticated Provisioning",
"Unauthenticated_Provisioning" : "Unauthenticated_Provisioning",
"UnHold" : "UnHold",
"United States" : "United States",
"UnMute" : "UnMute",
"Unregister When Reboot" : "Unregister When Reboot",
"Up" : "Up",
"Update" : "Update",
"Update Time Interval(Seconds)" : "Update Time Interval (Seconds)",
"Upgrade" : "Upgrade",
"Upgrade All" : "Upgrade All",
"upgrade:handsetupgrading" : "Upgrade: Handset upgrading...",
"Upload" : "Upload",
"Upload license success!" : "Upload license successfully!",
"Upload Photo" : "Upload Photo",
"Upload success!" : "Upload success!",
"Upload VPN Config" : "Upload VPN Config",
"Uploading, please wait ..." : "Uploading, please wait ...",
"Uptime" : "Uptime",
"URL" : "URL",
"URL Record" : "URL Record",
"Use Headset" : "Use Headset",
"Use Headset & Speaker" : "Use Headset & Speaker",
"Use Outbound Proxy In Dialog" : "Use Outbound Proxy In Dialog",
"Use Speaker" : "Use Speaker",
"User" : "User",
"User ID" : "User ID",
"User Name" : "Username",
"User Type" : "User Type",
"user-level messages" : "User-level Messages",
"Username" : "Username",
"UUCP subsystem" : "UUCP Subsystem",
"VAD" : "VAD",
"Value" : "Value",
"Value shouldn't be empty !" : "Value cannot be empty!",
"var" : "Var",
"Verify license failed!" : "Verify license failed!",
"Version" : "Version",
"Version 2" : "Version 2",
"Version 3" : "Version 3",
"VID (1-4094)" : "VID (1-4094)",
"Visual Alert for BLF Pickup" : "Visual Alert for BLF Pickup",
"Visual Alert For Parked Call" : "Visual Alert for Parked Call",
"VLAN" : "VLAN",
"Voice" : "Voice",
"Voice Mail" : "Voice Mail",
"Voice Mail Display" : "Voice Mail Display",
"Voice Mail Power Light Flash" : "Voice Mail Power LED Flash",
"Voice Mail Tone" : "Voice Mail Tone",
"Voice Mail without PIN" : "Voice Mail Without PIN",
"Voice Monitoring" : "Voice Monitoring",
"Voice QoS" : "Voice Qos",
"Voice QoS (0~63)" : "Voice QoS (0~63)",
"Voice RTCP-XR Report" : "Voice RTCP-XR Report",
"Voice/Text Mail Power Light Flash" : "Voice/Text Mail Power Light Flash",
"Voice_QoS can not be empty." : "Voice QoS cannot be empty!",
"VoIP Status" : "VoIP Status",
"VPN" : "VPN",
"VQ RTCP-XR Collector Address" : "VQ RTCP-XR Collector Address",
"VQ RTCP-XR Collector Name" : "VQ RTCP-XR Collector Name",
"VQ RTCP-XR Collector Port" : "VQ RTCP-XR Collector Port",
"VQ RTCP-XR Interval Report" : "VQ RTCP-XR Interval Report",
"VQ RTCP-XR Session Report" : "VQ RTCP-XR Session Report",
"Wallpaper" : "Wallpaper",
"WAN IP Address" : "WAN IP Address",
"WAN IP address is invalid!" : "WAN IP address is invalid!",
"WAN IPv6 address is invalid!" : "WAN IPv6 address is invalid!",
"WAN Port" : "WAN Port",
"WAN Port Status" : "WAN Port Status",
"WAN Port Type" : "WAN Port Type",
"Warning Threshold For Delay" : "Warning Threshold for Delay",
"Warning Threshold For Moslq" : "Warning Threshold for Moslq",
"Warning,AccountNATUDPUpdateTime could not be empty!" : "Warning,Account NAT UDP UpdateTime could not be empty!",
"Warning,the character '&' could not be contain!" : "Warning: the character & cannot be contained!",
"Warning: Group already exist!" : "Warning: Group already existed!",
"Warning: PSK could not be empty!" : "Warning: PSK cannot be empty!",
"Warning: Same Profile Name already exist!" : "Warning: Profile name already exists!",
"Warning: Some settings you changed take effect when you restart your machine! Do you want to reboot now?" : "Warning: The changes require a phone restart to take effect. Do you want to restart now?",
"Warning: SSID could not be empty!" : "Warning: SSID cannot be empty!",
"Warning: The Phone must be reboot to make BroadsoftActive take effect,do you want to reboot now?" : "Warning: Please reboot the phone to make Broadsoft Active take effect. Do you want to reboot it now?",
"Warning: The Phone must be reboot to make UC Active take effect,do you want to reboot now?" : "Warning: Please reboot the phone to make UC Active take effect. Do you want to reboot it now?",
"Warning: The Phone must be reboot to make XSI Active take effect,do you want to reboot now?" : "Warning: Please reboot the phone to make XSI Active take effect. Do you want to reboot it now?",
"Warning:Same port!" : "Warning:Same port!",
"Watch Dog" : "Watch Dog",
"Web" : "Web",
"Web Server" : "Web Server",
"Web_Configuration" : "Web Configuration",
"Wed" : "Wed",
"wednesday" : "Wednesday",
"Weekly" : "Weekly",
"Weekly Upgrade Interval(0~12week)" : "Weekly Upgrade Interval (0~12week)",
"WWW DD MMM" : "WWW DD MMM",
"WWW MMM DD" : "WWW MMM DD",
"XML Group" : "XML Group",
"XMLMenu" : "XMLDir",
"XMPP Account" : "XMPP Account",
"XMPP Password" : "XMPP Password",
"XMPP Username" : "XMPP Username",
"XSI" : "XSI",
"XSI Account" : "XSI Account",
"XSI Active" : "XSI Active",
"XSI Port should be between 1 and 65535!!" : "XSI Port should be between 1 and 65535!!",
"XSI Server Type" : "XSI Server Type",
"Year" : "Year",
"You are using the Internet Explorer with old version and some features may not work properly. Please upgrade your browser to the latest version." : "You are using the Internet Explorer with old version and some features may not work properly. Please upgrade your browser to the latest version.",
"You can click here to get more guides." : "Click here to get more product documents.",
"You have changed the password!" : "The password is changed!",
"You have changed the pin code!" : "The PIN code is changed!",
"You have to upload your picture when choose this type!" : "Please upload at least one picture if you choose this type.",
"You should input at least one outbound proxy server address!" : "You should input at least one outbound proxy server address!",
"You should input at least one SIP server address!" : "You should input at least one SIP server address!",
"YY/MM/DD" : "YY/MM/DD",
"YY-MM-DD" : "YY-MM-DD",
"YYYY MM DD" : "YYYY MM DD",
"YYYY/MM/DD" : "YYYY/MM/DD",
"YYYY-MM-DD" : "YYYY-MM-DD",
"Zero Touch" : "Zero Touch",
"Self-Define RSA Pri Key" : "Self-Define RSA Pri Key",
"Import RSA Pri Key" : "Import RSA Pri Key",
"PEAP" : "PEAP",
"TTLS" : "TTLS",
"PWD" : "PWD",
"Delete the wifi?" : "Delete the Wi-Fi?",
"unspecified" : "Unspecified",
"XML Park" : "XML Park",
"Hebrew" : "עִבְרִית (Hebrew)",
"Arabic" : "العربية (Arabic)",
"Alarm Number" : "Alarm Number",
"Alarm" : "Alarm",
"Alarm Template" : "Alarm Template",
"Alarm Name" : "Alarm Name",
"Alarm Type" : "Alarm Type",
"Stop Alarm From Handset" : "Stop Alarm From Handset",
"Trigger Delay" : "Trigger Delay",
"Stop Pre-Alarm From Handset" : "Stop Pre-Alarm From Handset",
"Pre-Alarm Delay" : "Pre-Alarm Delay",
"Button" : "Button",
"Man Down" : "Man Down",
"No Movement" : "No Movement",
"Layer 2 Tunneling Protocol(L2TP)" : "Layer 2 Tunneling Protocol (L2TP)",
"L2TP Server Address" : "L2TP Server Address",
"Authentication Name" : "Authentication Name",
"Authentication Password" : "Authentication Password",
"OpenVPN" : "OpenVPN",
"Import VPN Configuration File" : "Import VPN Configuration File",
"Export VPN Configuration File" : "Export VPN Configuration File",
"(1~4s)" : "(1~4s)",
"Register New Handsets" : "Register New Handsets",
"Register&Paging" : "Register&Paging",
"Alarm Assignment" : "Alarm Assignment",
"Config to" : "Config to",
"Alarm Line" : "Alarm Line",
"Alarm Selected" : "Alarm Selected",
"Common Alarm Server" : "Common Alarm Server",
"Please select at least one rom file." : "Please select at least one rom file.",
"Hidden Local Number" : "Hidden Local Number",
"Selected" : "Selected",
"Number Of Active Handsets" : "Number Of Active Handsets",
"Ring" : "Ring",
"Registered Power LED Flash" : "Registered Power LED Flash",
"Display Caller Party Information" : "Display Caller Party Information",
"Update Interval (15~86400s)" : "Update Interval (15~86400s)",
"Preference" : "Preference",
"Sunday" : "Sunday",
"Monday" : "Monday",
"Tuesday" : "Tuesday",
"Wednesday" : "Wednesday",
"Thursday" : "Thursday",
"Friday" : "Friday",
"Saturday" : "Saturday",
"All Handsets" : "All handsets",
"Handset" : "Handset",

_END_TRANS:null
}